### ISSUE TITLE
Define requirements for geodata and download data

### ISSUE THREAD

**Issue by nottrobin** [canonical-websites/snapcraft-flask#35]
_From @nottrobin on September 11, 2017 13:42_

@carlaberkers @nottrobin @bartaz @matthewpaulthomas meet to discuss what questions need answering so we can understand the shape of geodata and download data that should be exposed by the snap store API.

Answer as many of those questions as possible.

_Copied from original issue: canonical-websites/snapcraft.io#372_

**Comment by matthewpaulthomas** [comment]
Duplicate of #36.
